### ISSUE TITLE
a few encoding errors and validating whole collection

### ISSUE THREAD

**Issue by emylonas** [briancroxall/atalanta#3]
In emblems 1, 2 
there are some cases of `<subs>` instead of `<subst>`

also a few cases  of `<org>` instead of `<orig>`

you'll see them by editing the file in oxygen and looking for the red lines in the margin. Clicking the red line should take you to the error.

You can validate the whole collection (worth doing every now and then) by right clicking the "english translation" folder in your Oxygen (or the top folder holding the files you are working on) and then selecting the "validate" menu item, towards the bottom, then "validate" again from the slider submenu. This will validate all the files and show you any TEI errors.

**Comment by emylonas** [comment]
see also `<orgName>` in emblem 31

**Comment by geoellio** [comment]
Thanks for letting me know that shortcut Elli. I think I caught them all. Oxygen says there are no longer any problem tags.

**Comment by emylonas** [comment]
Yay! closed with  deea654
